import type { Feature } from '@doctor/contracts';

export const features: Feature[] = [
  {
    id: 'dashboard',
    name: '医生工作台',
    domain: 'platform',
    status: 'demo',
    description: '按当前登录医生的授权范围汇总患者、问诊、病历和健康任务。',
    iteration: 'Local demo 2026-09',
  },
  {
    id: 'patients',
    name: '患者档案检索',
    domain: 'patients',
    status: 'demo',
    description: '支持授权范围内的检索、疾病和状态筛选与分页。',
    iteration: 'Iteration 1',
  },
  {
    id: 'identity',
    name: '统一身份与分级授权',
    domain: 'platform',
    status: 'demo',
    description:
      '密码、测试邮箱验证码、会话撤销和患者范围已接通；照片仅演示采集核验，未接入人脸识别或短信验证码。',
    iteration: 'Local demo 2026-09',
  },
  {
    id: 'patient-edit',
    name: '患者档案维护',
    domain: 'patients',
    status: 'demo',
    description: '合成患者建档、保存、历史、分组、批量状态、归档与转交。',
    iteration: 'Iteration 1',
  },
  {
    id: 'encounter-chat',
    name: '图文在线问诊',
    domain: 'encounters',
    status: 'demo',
    description: '本地接诊、图文消息、状态保存与会话文本导出；不代表已连接真实患者客户端。',
    iteration: 'Local demo 2026-09',
  },
  {
    id: 'rtc',
    name: '视频问诊与录制',
    domain: 'encounters',
    status: 'planned',
    description: '当前只有本机摄像头预览；双端音视频、录制存储和回放尚未实现，不标记媒体已保存。',
    iteration: 'Iteration 3',
  },
  {
    id: 'records',
    name: '结构化病历与医嘱',
    domain: 'clinical',
    status: 'demo',
    description: '本地提交、审核、归档、修订、医嘱及固定病历版本的会诊材料引用。',
    iteration: 'Iteration 2',
  },
  {
    id: 'remote-consultation',
    name: '多学科远程会诊',
    domain: 'encounters',
    status: 'demo',
    description:
      '创建、受邀讨论、报告汇编、成员鉴权及完成后撤权已接通；病历选段正文阅读和真实媒体仍待 C/D 完善。',
    iteration: 'Local demo 2026-09',
  },
  {
    id: 'health-monitoring',
    name: '健康数据与个性化计划',
    domain: 'health',
    status: 'demo',
    description: '合成观察值、趋势、计划版本与评估可保存；真实医院和设备数据未接入。',
    iteration: 'Iterations 2–4',
  },
  {
    id: 'notifications',
    name: '自动随访提醒',
    domain: 'health',
    status: 'demo',
    description:
      '到期任务自动进入持久化本地患者测试收件箱；短信和邮件为本地模拟通道，不向真实患者发送。',
    iteration: 'Local demo 2026-09',
  },
  {
    id: 'hospital-sync',
    name: '医院及设备数据接入',
    domain: 'platform',
    status: 'planned',
    description: '对接契约已预留，尚未配置外部服务。',
    iteration: 'Iteration 4',
  },
  {
    id: 'audit',
    name: '个人操作日志',
    domain: 'platform',
    status: 'demo',
    description: '当前医生的真实访问与操作记录，支持服务端筛选、分页及 CSV 导出。',
    iteration: 'Local demo 2026-09',
  },
  {
    id: 'settings',
    name: '医生资料与提醒偏好',
    domain: 'platform',
    status: 'demo',
    description: '医生资料和通知偏好按账号保存在数据库；免打扰控制设备弹窗，站内记录仍保留。',
    iteration: 'Local demo 2026-09',
  },
  {
    id: 'community',
    name: '同行交流空间',
    domain: 'social',
    status: 'demo',
    description: '可选本地社区支持内容、回复和实时通知，保留独立启用开关，不自动共享临床数据。',
    iteration: 'Iteration 5',
  },
];
