import type { Feature } from '@doctor/contracts';
export const features: Feature[] = [
  {
    id: 'dashboard',
    name: '医生工作台',
    domain: 'platform',
    status: 'demo',
    description: '合成数据概览、日程与待办展示。',
    iteration: 'Iteration 0',
  },
  {
    id: 'patients',
    name: '患者档案检索',
    domain: 'patients',
    status: 'demo',
    description: '支持演示患者检索、状态筛选与档案预览。',
    iteration: 'Iteration 0',
  },
  {
    id: 'identity',
    name: '统一身份与分级授权',
    domain: 'platform',
    status: 'planned',
    description: '邮箱、短信与人脸验证需对接统一身份服务。当前仅固定演示身份。',
    iteration: 'Iteration 1',
  },
  {
    id: 'patient-edit',
    name: '患者档案维护',
    domain: 'patients',
    status: 'planned',
    description: '资料维护、档案版本与批量分组将在基础迭代实现。',
    iteration: 'Iteration 1',
  },
  {
    id: 'encounter-chat',
    name: '图文在线问诊',
    domain: 'encounters',
    status: 'planned',
    description: '接诊、消息、附件与自动归档接口已预留。',
    iteration: 'Iterations 1–3',
  },
  {
    id: 'rtc',
    name: '视频问诊与录制',
    domain: 'encounters',
    status: 'planned',
    description: '需接入 RTC、知情授权、录制和对象存储服务。',
    iteration: 'Iteration 3',
  },
  {
    id: 'records',
    name: '结构化病历与医嘱',
    domain: 'clinical',
    status: 'planned',
    description: '草稿、医嘱版本、上级审核与归档待上线。',
    iteration: 'Iteration 2',
  },
  {
    id: 'remote-consultation',
    name: '多学科远程会诊',
    domain: 'encounters',
    status: 'planned',
    description: '会诊临时授权、协作与医生确认报告待上线。',
    iteration: 'Iteration 3',
  },
  {
    id: 'health-monitoring',
    name: '健康数据与个性化计划',
    domain: 'health',
    status: 'planned',
    description: '当前仅展示合成趋势；设备接入、计划评估待上线。',
    iteration: 'Iterations 2–4',
  },
  {
    id: 'notifications',
    name: '自动随访提醒',
    domain: 'health',
    status: 'planned',
    description: '任务表与通知适配接口已预留，当前不发送任何消息。',
    iteration: 'Iterations 2–4',
  },
  {
    id: 'hospital-sync',
    name: '医院及设备数据接入',
    domain: 'platform',
    status: 'planned',
    description: '对接契约已预留，尚未配置外部服务。',
    iteration: 'Iteration 4',
  },
  {
    id: 'audit',
    name: '个人操作日志',
    domain: 'platform',
    status: 'demo',
    description: '可查看本演示身份的样例事件和本机访问事件。',
    iteration: 'Iteration 0',
  },
  {
    id: 'community',
    name: '同行交流空间',
    domain: 'social',
    status: 'disabled',
    description: '可选独立扩展，后端服务默认关闭；前端展示预览入口，无临床数据自动同步。',
    iteration: 'Iteration 5',
  },
];
