-- CareLink SQLite schema snapshot. Generated by npm run database:export.
-- Runtime source of truth: apps/api/src/**/**migration*.ts.
PRAGMA foreign_keys=ON;
BEGIN;
-- table: access_grants
CREATE TABLE access_grants (
      id TEXT PRIMARY KEY, identity_id TEXT NOT NULL REFERENCES identities(id), patient_id TEXT NOT NULL REFERENCES patients(id),
      scope TEXT NOT NULL, task_id TEXT REFERENCES consultations(id), expires_at TEXT, revoked_at TEXT,
      created_at TEXT NOT NULL, CHECK(task_id IS NULL OR expires_at IS NOT NULL)
    );
-- table: attachments
CREATE TABLE attachments (
      id TEXT PRIMARY KEY, patient_id TEXT NOT NULL REFERENCES patients(id), encounter_id TEXT REFERENCES encounters(id),
      consultation_id TEXT REFERENCES consultations(id), object_key TEXT NOT NULL UNIQUE,
      mime_type TEXT NOT NULL, byte_length INTEGER NOT NULL CHECK(byte_length>=0),
      uploaded_by TEXT REFERENCES identities(id), uploaded_at TEXT NOT NULL, scan_status TEXT NOT NULL DEFAULT 'pending'
    );
-- table: audit_events
CREATE TABLE audit_events (
      id TEXT PRIMARY KEY, actor_id TEXT NOT NULL REFERENCES identities(id), action TEXT NOT NULL,
      target_type TEXT NOT NULL, target_id TEXT NOT NULL, occurred_at TEXT NOT NULL,
      outcome TEXT NOT NULL CHECK(outcome IN ('success','denied','planned')), description TEXT NOT NULL
    );
-- table: care_plan_versions
CREATE TABLE care_plan_versions (
      id TEXT PRIMARY KEY, plan_id TEXT NOT NULL REFERENCES care_plans(id), version INTEGER NOT NULL CHECK(version>0),
      payload_json TEXT NOT NULL, authored_by TEXT NOT NULL REFERENCES identities(id), created_at TEXT NOT NULL,
      UNIQUE(plan_id,version)
    );
-- table: care_plans
CREATE TABLE care_plans (
      id TEXT PRIMARY KEY, patient_id TEXT NOT NULL REFERENCES patients(id), doctor_id TEXT NOT NULL REFERENCES identities(id),
      title TEXT NOT NULL, status TEXT NOT NULL CHECK(status IN ('active','draft')), goals_json TEXT NOT NULL,
      next_review TEXT NOT NULL, completion_percent INTEGER NOT NULL CHECK(completion_percent BETWEEN 0 AND 100)
    , current_version INTEGER NOT NULL DEFAULT 1 CHECK(current_version > 0), created_at TEXT NOT NULL DEFAULT '2026-09-01T00:00:00+08:00', updated_at TEXT NOT NULL DEFAULT '2026-09-01T00:00:00+08:00');
-- table: clinical_command_receipts
CREATE TABLE clinical_command_receipts (
      actor_id TEXT NOT NULL REFERENCES identities(id),
      operation TEXT NOT NULL,
      record_id TEXT NOT NULL REFERENCES medical_records(id),
      request_key TEXT NOT NULL,
      request_hash TEXT NOT NULL,
      created_at TEXT NOT NULL,
      PRIMARY KEY(actor_id, operation, record_id, request_key)
    );
-- table: clinical_material_receipts
CREATE TABLE clinical_material_receipts (
      actor_id TEXT NOT NULL REFERENCES identities(id),
      operation TEXT NOT NULL,
      resource_id TEXT NOT NULL,
      request_key TEXT NOT NULL,
      request_hash TEXT NOT NULL,
      material_id TEXT NOT NULL REFERENCES clinical_materials(id),
      created_at TEXT NOT NULL,
      PRIMARY KEY(actor_id, operation, resource_id, request_key)
    );
-- table: clinical_materials
CREATE TABLE clinical_materials (
      id TEXT PRIMARY KEY,
      consultation_id TEXT NOT NULL REFERENCES consultations(id),
      patient_id TEXT NOT NULL REFERENCES patients(id),
      record_id TEXT NOT NULL REFERENCES medical_records(id),
      record_version INTEGER NOT NULL CHECK(record_version>0),
      shared_sections_json TEXT NOT NULL,
      purpose TEXT NOT NULL,
      created_by TEXT NOT NULL REFERENCES identities(id),
      created_at TEXT NOT NULL,
      report_id TEXT,
      linked_at TEXT,
      FOREIGN KEY(record_id, record_version) REFERENCES medical_record_versions(record_id, version)
    );
-- table: clinical_order_receipts
CREATE TABLE clinical_order_receipts (
      actor_id TEXT NOT NULL REFERENCES identities(id),
      operation TEXT NOT NULL,
      resource_id TEXT NOT NULL,
      request_key TEXT NOT NULL,
      request_hash TEXT NOT NULL,
      order_id TEXT NOT NULL REFERENCES medical_orders(id),
      created_at TEXT NOT NULL,
      PRIMARY KEY(actor_id, operation, resource_id, request_key)
    );
-- table: consultation_participants
CREATE TABLE consultation_participants (
      consultation_id TEXT NOT NULL REFERENCES consultations(id), identity_id TEXT NOT NULL REFERENCES identities(id),
      participant_role TEXT NOT NULL, joined_at TEXT, left_at TEXT,
      PRIMARY KEY(consultation_id,identity_id)
    );
-- table: consultation_reports
CREATE TABLE consultation_reports (
      id TEXT PRIMARY KEY, consultation_id TEXT NOT NULL REFERENCES consultations(id), version INTEGER NOT NULL CHECK(version>0),
      body_json TEXT NOT NULL, status TEXT NOT NULL CHECK(status IN ('draft','confirmed','archived')),
      confirmed_by TEXT REFERENCES identities(id), confirmed_at TEXT, created_at TEXT NOT NULL,
      UNIQUE(consultation_id,version), CHECK(status='draft' OR (confirmed_by IS NOT NULL AND confirmed_at IS NOT NULL))
    );
-- table: consultations
CREATE TABLE consultations (
      id TEXT PRIMARY KEY, patient_id TEXT NOT NULL REFERENCES patients(id), requested_by TEXT NOT NULL REFERENCES identities(id),
      title TEXT NOT NULL, specialty TEXT NOT NULL, status TEXT NOT NULL CHECK(status IN ('requested','scheduled','completed')),
      scheduled_at TEXT NOT NULL, summary TEXT NOT NULL, completed_at TEXT
    );
-- table: doctors
CREATE TABLE doctors (
      identity_id TEXT PRIMARY KEY REFERENCES identities(id),
      license_number TEXT NOT NULL UNIQUE,
      specialty TEXT NOT NULL,
      phone TEXT NOT NULL,
      government_id_type TEXT NOT NULL,
      government_id_masked TEXT NOT NULL,
      credential_status TEXT NOT NULL CHECK(credential_status IN ('pending','verified','rejected')),
      personnel_status TEXT NOT NULL CHECK(personnel_status IN ('pending','verified','suspended')),
      enabled INTEGER NOT NULL DEFAULT 1 CHECK(enabled IN (0,1)),
      created_at TEXT NOT NULL,
      updated_at TEXT NOT NULL
    );
-- table: email_challenges
CREATE TABLE email_challenges (
      id TEXT PRIMARY KEY,
      user_id TEXT NOT NULL REFERENCES users(id),
      purpose TEXT NOT NULL DEFAULT 'login',
      code_hash TEXT NOT NULL,
      attempts INTEGER NOT NULL DEFAULT 0,
      expires_at TEXT NOT NULL,
      consumed_at TEXT,
      photo_ticket_hash TEXT,
      photo_ticket_expires_at TEXT,
      created_at TEXT NOT NULL
    );
-- table: encounter_messages
CREATE TABLE encounter_messages (
      id TEXT PRIMARY KEY, encounter_id TEXT NOT NULL REFERENCES encounters(id), sender_identity_id TEXT REFERENCES identities(id),
      sender_patient_id TEXT REFERENCES patients(id), body TEXT NOT NULL, sent_at TEXT NOT NULL,
      CHECK((sender_identity_id IS NOT NULL) != (sender_patient_id IS NOT NULL))
    );
-- table: encounters
CREATE TABLE encounters (
      id TEXT PRIMARY KEY, patient_id TEXT NOT NULL REFERENCES patients(id), doctor_id TEXT NOT NULL REFERENCES identities(id),
      type TEXT NOT NULL CHECK(type IN ('video','text')), status TEXT NOT NULL CHECK(status IN ('waiting','scheduled','completed')),
      scheduled_at TEXT NOT NULL, reason TEXT NOT NULL, duration_minutes INTEGER NOT NULL CHECK(duration_minutes>=0),
      rtc_room_id TEXT, ended_at TEXT, archived_at TEXT
    );
-- table: feature_settings
CREATE TABLE feature_settings (
      id TEXT PRIMARY KEY, enabled INTEGER NOT NULL DEFAULT 0 CHECK(enabled IN (0,1)),
      configured_by TEXT REFERENCES identities(id), updated_at TEXT NOT NULL
    );
-- table: health_alerts
CREATE TABLE health_alerts (
      id TEXT PRIMARY KEY, patient_id TEXT NOT NULL REFERENCES patients(id), metric TEXT NOT NULL, value TEXT NOT NULL,
      severity TEXT NOT NULL CHECK(severity IN ('attention','review')), measured_at TEXT NOT NULL,
      source_label TEXT NOT NULL, description TEXT NOT NULL, reviewed_at TEXT, reviewed_by TEXT REFERENCES identities(id)
    );
-- table: health_assessments
CREATE TABLE health_assessments (
      id TEXT PRIMARY KEY, patient_id TEXT NOT NULL REFERENCES patients(id), plan_id TEXT REFERENCES care_plans(id),
      assessor_id TEXT NOT NULL REFERENCES identities(id), assessed_at TEXT NOT NULL, summary TEXT NOT NULL,
      recommendations_json TEXT NOT NULL, next_review TEXT
    );
-- table: health_command_receipts
CREATE TABLE health_command_receipts (
      actor_id TEXT NOT NULL,
      command_id TEXT NOT NULL,
      operation TEXT NOT NULL,
      request_digest TEXT NOT NULL,
      resource_id TEXT NOT NULL,
      response_json TEXT NOT NULL,
      created_at TEXT NOT NULL,
      PRIMARY KEY(actor_id,command_id)
    );
-- table: health_notification_preferences
CREATE TABLE health_notification_preferences (
      patient_id TEXT PRIMARY KEY,
      enabled INTEGER NOT NULL DEFAULT 1 CHECK(enabled IN (0,1)),
      updated_at TEXT NOT NULL
    );
-- table: health_observation_confirmations
CREATE TABLE health_observation_confirmations (
      id TEXT PRIMARY KEY,
      observation_id TEXT NOT NULL REFERENCES health_observations(id),
      confirmed_by TEXT NOT NULL REFERENCES identities(id),
      confirmed_at TEXT NOT NULL,
      note TEXT,
      before_json TEXT NOT NULL,
      after_json TEXT NOT NULL
    );
-- table: health_observations
CREATE TABLE health_observations (
      id TEXT PRIMARY KEY,
      patient_id TEXT NOT NULL REFERENCES patients(id),
      metric TEXT NOT NULL CHECK(metric IN ('systolic','diastolic','glucose','heart-rate')),
      value REAL NOT NULL,
      unit TEXT NOT NULL,
      measured_at TEXT NOT NULL,
      received_at TEXT NOT NULL,
      source TEXT NOT NULL CHECK(source IN ('synthetic-demo','manual-entry','device-simulator','patient-upload')),
      source_label TEXT NOT NULL,
      external_observation_id TEXT,
      quality_status TEXT NOT NULL DEFAULT 'demo',
      recorded_by TEXT REFERENCES identities(id),
      confirmed_by TEXT REFERENCES identities(id),
      confirmed_at TEXT,
      UNIQUE(patient_id,source,external_observation_id)
    );
-- table: health_reminder_delivery_attempts
CREATE TABLE health_reminder_delivery_attempts (
      actor_id TEXT NOT NULL REFERENCES identities(id), command_id TEXT NOT NULL,
      reminder_id TEXT NOT NULL REFERENCES reminder_tasks(id), provider_idempotency_key TEXT NOT NULL UNIQUE,
      status TEXT NOT NULL CHECK(status IN ('pending','sent','failed')), created_at TEXT NOT NULL,
      completed_at TEXT, PRIMARY KEY(actor_id,command_id)
    );
-- table: identities
CREATE TABLE identities (
      id TEXT PRIMARY KEY, display_name TEXT NOT NULL, title TEXT NOT NULL,
      department TEXT NOT NULL, hospital TEXT NOT NULL, avatar_initials TEXT NOT NULL,
      identity_provider_subject TEXT UNIQUE, is_synthetic INTEGER NOT NULL DEFAULT 1 CHECK(is_synthetic=1)
    );
-- table: identity_photo_checks
CREATE TABLE identity_photo_checks (
      id TEXT PRIMARY KEY,
      user_id TEXT NOT NULL REFERENCES users(id),
      photo_object_key TEXT NOT NULL,
      capture_method TEXT NOT NULL CHECK(capture_method IN ('camera','upload')),
      status TEXT NOT NULL DEFAULT 'demo-accepted' CHECK(status IN ('demo-accepted','rejected')),
      demo_only INTEGER NOT NULL DEFAULT 1 CHECK(demo_only=1),
      checked_at TEXT NOT NULL,
      reviewer_note TEXT NOT NULL DEFAULT 'Course demonstration only; no biometric comparison performed.'
    );
-- table: identity_roles
CREATE TABLE identity_roles (
      identity_id TEXT NOT NULL REFERENCES identities(id), role_id TEXT NOT NULL REFERENCES roles(id),
      PRIMARY KEY(identity_id, role_id)
    );
-- table: medical_order_versions
CREATE TABLE medical_order_versions (
      id TEXT PRIMARY KEY, order_id TEXT NOT NULL REFERENCES medical_orders(id), version INTEGER NOT NULL CHECK(version>0),
      payload_json TEXT NOT NULL, authored_by TEXT NOT NULL REFERENCES identities(id), authored_at TEXT NOT NULL,
      change_reason TEXT NOT NULL, template_id TEXT NOT NULL DEFAULT 'examination', template_version INTEGER NOT NULL DEFAULT 1 CHECK(template_version>0), UNIQUE(order_id,version)
    );
-- table: medical_orders
CREATE TABLE medical_orders (
      id TEXT PRIMARY KEY, record_id TEXT NOT NULL REFERENCES medical_records(id), patient_id TEXT NOT NULL REFERENCES patients(id),
      type TEXT NOT NULL CHECK(type IN ('medication','examination','laboratory')),
      status TEXT NOT NULL CHECK(status IN ('draft','active','stopped')),
      current_version INTEGER NOT NULL CHECK(current_version>0), created_by TEXT NOT NULL REFERENCES identities(id),
      created_at TEXT NOT NULL, stopped_at TEXT, stop_reason TEXT
    );
-- table: medical_record_versions
CREATE TABLE medical_record_versions (
      id TEXT PRIMARY KEY, record_id TEXT NOT NULL REFERENCES medical_records(id), version INTEGER NOT NULL CHECK(version>0),
      template_id TEXT NOT NULL, body_json TEXT NOT NULL, authored_by TEXT NOT NULL REFERENCES identities(id),
      authored_at TEXT NOT NULL, amendment_reason TEXT, template_version INTEGER NOT NULL DEFAULT 1 CHECK(template_version>0), title TEXT, diagnosis TEXT, UNIQUE(record_id,version)
    );
-- table: medical_records
CREATE TABLE medical_records (
      id TEXT PRIMARY KEY, patient_id TEXT NOT NULL REFERENCES patients(id), encounter_id TEXT REFERENCES encounters(id),
      title TEXT NOT NULL, diagnosis TEXT NOT NULL,
      status TEXT NOT NULL CHECK(status IN ('draft','pending-review','archived')),
      author_id TEXT NOT NULL REFERENCES identities(id), updated_at TEXT NOT NULL,
      version INTEGER NOT NULL CHECK(version>0), archived_at TEXT
    );
-- table: outbox_events
CREATE TABLE outbox_events (
      id TEXT PRIMARY KEY, event_type TEXT NOT NULL, schema_version INTEGER NOT NULL DEFAULT 1,
      aggregate_id TEXT NOT NULL, payload_json TEXT NOT NULL, created_at TEXT NOT NULL,
      processed_at TEXT, attempts INTEGER NOT NULL DEFAULT 0, last_error TEXT,
      idempotency_key TEXT NOT NULL UNIQUE
    );
-- table: patient_archive_baselines
CREATE TABLE patient_archive_baselines (
      patient_id TEXT PRIMARY KEY REFERENCES patients(id),
      version INTEGER NOT NULL,
      payload_json TEXT NOT NULL,
      captured_at TEXT NOT NULL
    );
-- table: patient_archive_versions
CREATE TABLE patient_archive_versions (
      id TEXT PRIMARY KEY, patient_id TEXT NOT NULL REFERENCES patients(id), version INTEGER NOT NULL CHECK(version>0),
      payload_json TEXT NOT NULL, authored_by TEXT NOT NULL REFERENCES identities(id), created_at TEXT NOT NULL,
      change_reason TEXT NOT NULL, UNIQUE(patient_id,version)
    );
-- table: patient_registration_requests
CREATE TABLE patient_registration_requests (
    actor_id TEXT NOT NULL REFERENCES identities(id),
    request_key TEXT NOT NULL,
    request_hash TEXT NOT NULL,
    patient_id TEXT NOT NULL REFERENCES patients(id),
    created_at TEXT NOT NULL,
    PRIMARY KEY(actor_id,request_key)
  );
-- table: patients
CREATE TABLE patients (
      id TEXT PRIMARY KEY, name TEXT NOT NULL, gender TEXT NOT NULL CHECK(gender IN ('女','男')),
      age INTEGER NOT NULL CHECK(age BETWEEN 0 AND 130), phone TEXT NOT NULL,
      diagnosis TEXT NOT NULL, tags_json TEXT NOT NULL, status TEXT NOT NULL CHECK(status IN ('stable','attention','follow-up')),
      last_visit TEXT NOT NULL, next_follow_up TEXT NOT NULL,
      assigned_doctor_id TEXT NOT NULL REFERENCES identities(id), allergies_json TEXT NOT NULL,
      medical_history_json TEXT NOT NULL, care_summary TEXT NOT NULL,
      is_synthetic INTEGER NOT NULL DEFAULT 1 CHECK(is_synthetic=1)
    , symptoms_json TEXT NOT NULL DEFAULT '[]', allergy_status TEXT NOT NULL DEFAULT 'unknown'
      CHECK(allergy_status IN ('unknown','none','recorded')));
-- table: record_reviews
CREATE TABLE record_reviews (
      id TEXT PRIMARY KEY, record_id TEXT NOT NULL REFERENCES medical_records(id), record_version INTEGER NOT NULL,
      reviewer_id TEXT NOT NULL REFERENCES identities(id), decision TEXT NOT NULL CHECK(decision IN ('approved','returned')),
      comment TEXT NOT NULL, reviewed_at TEXT NOT NULL,
      FOREIGN KEY(record_id,record_version) REFERENCES medical_record_versions(record_id,version)
    );
-- table: recordings
CREATE TABLE recordings (
      id TEXT PRIMARY KEY, encounter_id TEXT NOT NULL REFERENCES encounters(id), provider_recording_id TEXT,
      object_key TEXT, consent_reference TEXT NOT NULL, consented_at TEXT NOT NULL,
      status TEXT NOT NULL CHECK(status IN ('requested','recording','processing','available','failed')),
      started_at TEXT, stopped_at TEXT, retention_until TEXT, failure_reason TEXT
    );
-- table: reminder_tasks
CREATE TABLE reminder_tasks (
      id TEXT PRIMARY KEY, patient_id TEXT NOT NULL REFERENCES patients(id), plan_id TEXT REFERENCES care_plans(id),
      channel TEXT NOT NULL CHECK(channel IN ('in-app','sms','email')), template_id TEXT NOT NULL, scheduled_at TEXT NOT NULL,
      status TEXT NOT NULL CHECK(status IN ('planned','pending','sent','failed','cancelled')), consent_reference TEXT,
      provider_message_id TEXT, attempts INTEGER NOT NULL DEFAULT 0, last_error TEXT, idempotency_key TEXT NOT NULL UNIQUE
    );
-- table: role_permissions
CREATE TABLE role_permissions (
      role_id TEXT NOT NULL REFERENCES roles(id), permission TEXT NOT NULL,
      PRIMARY KEY(role_id, permission)
    );
-- table: roles
CREATE TABLE roles (id TEXT PRIMARY KEY, name TEXT NOT NULL UNIQUE);
-- table: schema_migrations
CREATE TABLE schema_migrations (version INTEGER PRIMARY KEY, name TEXT NOT NULL, applied_at TEXT NOT NULL);
-- table: social_attachments
CREATE TABLE social_attachments (
      id TEXT PRIMARY KEY,
      owner_identity_id TEXT NOT NULL REFERENCES identities(id),
      kind TEXT NOT NULL CHECK(kind IN ('image','audio')),
      media_type TEXT NOT NULL,
      storage_key TEXT NOT NULL UNIQUE,
      byte_size INTEGER NOT NULL CHECK(byte_size >= 0),
      width INTEGER CHECK(width IS NULL OR width > 0),
      height INTEGER CHECK(height IS NULL OR height > 0),
      duration_ms INTEGER CHECK(duration_ms IS NULL OR duration_ms >= 0),
      state TEXT NOT NULL CHECK(state IN ('temporary','attached')),
      created_at TEXT NOT NULL,
      attached_at TEXT
    );
-- table: social_bookmarks
CREATE TABLE social_bookmarks (
      post_id TEXT NOT NULL REFERENCES social_posts(id), identity_id TEXT NOT NULL REFERENCES identities(id),
      created_at TEXT NOT NULL, PRIMARY KEY(post_id,identity_id)
    );
-- table: social_command_receipts
CREATE TABLE social_command_receipts (
      actor_id TEXT NOT NULL, command_id TEXT NOT NULL, operation TEXT NOT NULL, request_digest TEXT NOT NULL,
      resource_id TEXT NOT NULL, response_json TEXT NOT NULL, created_at TEXT NOT NULL,
      PRIMARY KEY(actor_id,command_id)
    );
-- table: social_comment_reactions
CREATE TABLE social_comment_reactions (
    comment_id TEXT NOT NULL REFERENCES social_comments(id),
    identity_id TEXT NOT NULL REFERENCES identities(id),
    kind TEXT NOT NULL CHECK(kind IN ('like','bookmark')),
    created_at TEXT NOT NULL,
    PRIMARY KEY(comment_id,identity_id,kind)
  );
-- table: social_comments
CREATE TABLE social_comments (
      id TEXT PRIMARY KEY, post_id TEXT NOT NULL REFERENCES social_posts(id), parent_comment_id TEXT REFERENCES social_comments(id),
      author_id TEXT NOT NULL REFERENCES identities(id), display_mode TEXT NOT NULL DEFAULT 'named' CHECK(display_mode IN ('named','anonymous')),
      body TEXT NOT NULL, created_at TEXT NOT NULL
    , deleted_at TEXT);
-- table: social_content_blocks
CREATE TABLE social_content_blocks (
      id TEXT PRIMARY KEY,
      entity_type TEXT NOT NULL CHECK(entity_type IN ('post','comment','message')),
      entity_id TEXT NOT NULL,
      display_order INTEGER NOT NULL CHECK(display_order >= 0),
      kind TEXT NOT NULL CHECK(kind IN ('image','audio','medical-metric-card')),
      attachment_id TEXT REFERENCES social_attachments(id),
      card_json TEXT,
      schema_version INTEGER NOT NULL DEFAULT 1 CHECK(schema_version = 1),
      created_at TEXT NOT NULL,
      UNIQUE(entity_type,entity_id,display_order),
      CHECK(
        (kind IN ('image','audio') AND attachment_id IS NOT NULL AND card_json IS NULL)
        OR
        (kind='medical-metric-card' AND attachment_id IS NULL AND card_json IS NOT NULL)
      )
    );
-- table: social_content_history
CREATE TABLE social_content_history (
      id TEXT PRIMARY KEY, entity_type TEXT NOT NULL, entity_id TEXT NOT NULL,
      actor_id TEXT NOT NULL REFERENCES identities(id), action TEXT NOT NULL,
      reason TEXT NOT NULL, before_json TEXT NOT NULL, after_json TEXT NOT NULL, created_at TEXT NOT NULL
    );
-- table: social_conversation_members
CREATE TABLE social_conversation_members (
      conversation_id TEXT NOT NULL REFERENCES social_conversations(id), identity_id TEXT NOT NULL REFERENCES identities(id),
      PRIMARY KEY(conversation_id,identity_id)
    );
-- table: social_conversations
CREATE TABLE social_conversations (id TEXT PRIMARY KEY, created_at TEXT NOT NULL, updated_at TEXT NOT NULL);
-- table: social_direct_messages
CREATE TABLE social_direct_messages (
      id TEXT PRIMARY KEY, sender_id TEXT NOT NULL REFERENCES identities(id), recipient_id TEXT NOT NULL REFERENCES identities(id),
      body TEXT NOT NULL, sent_at TEXT NOT NULL
    , conversation_id TEXT REFERENCES social_conversations(id), read_at TEXT);
-- table: social_groups
CREATE TABLE social_groups (id TEXT PRIMARY KEY, name TEXT NOT NULL, specialty TEXT NOT NULL, description TEXT NOT NULL DEFAULT '');
-- table: social_likes
CREATE TABLE social_likes (
      post_id TEXT NOT NULL REFERENCES social_posts(id), identity_id TEXT NOT NULL REFERENCES identities(id),
      created_at TEXT NOT NULL, PRIMARY KEY(post_id,identity_id)
    );
-- table: social_memberships
CREATE TABLE social_memberships (
      group_id TEXT NOT NULL REFERENCES social_groups(id), identity_id TEXT NOT NULL REFERENCES identities(id),
      joined_at TEXT NOT NULL, PRIMARY KEY(group_id,identity_id)
    );
-- table: social_notifications
CREATE TABLE social_notifications (
      id TEXT PRIMARY KEY, recipient_id TEXT NOT NULL REFERENCES identities(id),
      actor_id TEXT REFERENCES identities(id), post_id TEXT REFERENCES social_posts(id),
      comment_id TEXT REFERENCES social_comments(id),
      kind TEXT NOT NULL CHECK(kind IN ('comment','reply','like','bookmark','report-accepted','report-upheld','report-rejected','content-moderated')),
      created_at TEXT NOT NULL, read_at TEXT
    );
-- table: social_posts
CREATE TABLE social_posts (
      id TEXT PRIMARY KEY, group_id TEXT NOT NULL REFERENCES social_groups(id), author_id TEXT NOT NULL REFERENCES identities(id),
      display_mode TEXT NOT NULL CHECK(display_mode IN ('named','anonymous')), title TEXT NOT NULL, body TEXT NOT NULL,
      tags_json TEXT NOT NULL DEFAULT '[]', contains_case_material INTEGER NOT NULL DEFAULT 0 CHECK(contains_case_material IN (0,1)),
      deidentification_confirmed_at TEXT, moderation_status TEXT NOT NULL DEFAULT 'pending',
      created_at TEXT NOT NULL, last_activity_at TEXT NOT NULL
    , view_count INTEGER NOT NULL DEFAULT 0 CHECK(view_count >= 0));
-- table: social_preferences
CREATE TABLE social_preferences (
      identity_id TEXT PRIMARY KEY REFERENCES identities(id), enabled INTEGER NOT NULL DEFAULT 0 CHECK(enabled IN (0,1)),
      notifications_enabled INTEGER NOT NULL DEFAULT 0 CHECK(notifications_enabled IN (0,1)),
      updated_at TEXT NOT NULL, CHECK(enabled=1 OR notifications_enabled=0)
    );
-- table: social_reports
CREATE TABLE social_reports (
      id TEXT PRIMARY KEY, post_id TEXT REFERENCES social_posts(id), reported_message_id TEXT REFERENCES social_direct_messages(id),
      reporter_id TEXT NOT NULL REFERENCES identities(id), reason TEXT NOT NULL, description TEXT,
      status TEXT NOT NULL DEFAULT 'pending', reviewed_by TEXT REFERENCES identities(id), reviewed_at TEXT, created_at TEXT NOT NULL
    , comment_id TEXT REFERENCES social_comments(id));
-- table: user_sessions
CREATE TABLE user_sessions (
      id TEXT PRIMARY KEY,
      user_id TEXT NOT NULL REFERENCES users(id),
      token_hash TEXT NOT NULL UNIQUE,
      client_type TEXT NOT NULL DEFAULT 'desktop',
      auth_method TEXT NOT NULL DEFAULT 'face' CHECK(auth_method IN ('password','email','face')),
      created_at TEXT NOT NULL,
      last_used_at TEXT NOT NULL,
      expires_at TEXT NOT NULL,
      revoked_at TEXT,
      photo_check_id TEXT REFERENCES identity_photo_checks(id)
    );
-- table: users
CREATE TABLE users (
      id TEXT PRIMARY KEY,
      identity_id TEXT NOT NULL UNIQUE REFERENCES identities(id),
      username TEXT NOT NULL UNIQUE COLLATE NOCASE,
      email TEXT NOT NULL UNIQUE COLLATE NOCASE,
      email_verified_at TEXT,
      password_hash TEXT NOT NULL,
      status TEXT NOT NULL DEFAULT 'active' CHECK(status IN ('active','disabled','locked')),
      failed_login_count INTEGER NOT NULL DEFAULT 0,
      locked_until TEXT,
      created_at TEXT NOT NULL,
      updated_at TEXT NOT NULL
    );
-- index: access_grants_actor_patient
CREATE INDEX access_grants_actor_patient ON access_grants(identity_id, patient_id);
-- index: audit_events_actor_time
CREATE INDEX audit_events_actor_time ON audit_events(actor_id, occurred_at DESC);
-- index: clinical_materials_consultation
CREATE INDEX clinical_materials_consultation ON clinical_materials(consultation_id, created_at DESC);
-- index: clinical_orders_patient_status
CREATE INDEX clinical_orders_patient_status ON medical_orders(patient_id, status);
-- index: clinical_orders_record
CREATE INDEX clinical_orders_record ON medical_orders(record_id, created_at DESC);
-- index: clinical_records_encounter
CREATE INDEX clinical_records_encounter ON medical_records(encounter_id) WHERE encounter_id IS NOT NULL;
-- index: clinical_records_patient_updated
CREATE INDEX clinical_records_patient_updated ON medical_records(patient_id,updated_at DESC);
-- index: clinical_records_status_updated
CREATE INDEX clinical_records_status_updated ON medical_records(status,updated_at DESC);
-- index: email_challenges_user_time
CREATE INDEX email_challenges_user_time ON email_challenges(user_id,created_at DESC);
-- index: health_observation_confirmations_observation
CREATE INDEX health_observation_confirmations_observation
      ON health_observation_confirmations(observation_id,confirmed_at,id);
-- index: health_observations_patient_time
CREATE INDEX health_observations_patient_time
      ON health_observations(patient_id,measured_at);
-- index: patients_doctor_status
CREATE INDEX patients_doctor_status ON patients(assigned_doctor_id,status);
-- index: social_attachments_owner_state
CREATE INDEX social_attachments_owner_state
      ON social_attachments(owner_identity_id,state,created_at);
-- index: social_comments_post_time
CREATE INDEX social_comments_post_time ON social_comments(post_id,created_at,id);
-- index: social_content_blocks_entity
CREATE INDEX social_content_blocks_entity
      ON social_content_blocks(entity_type,entity_id,display_order);
-- index: social_history_entity
CREATE INDEX social_history_entity ON social_content_history(entity_type,entity_id,created_at);
-- index: social_messages_conversation_time
CREATE INDEX social_messages_conversation_time ON social_direct_messages(conversation_id,sent_at,id);
-- index: social_notifications_recipient_time
CREATE INDEX social_notifications_recipient_time ON social_notifications(recipient_id,created_at DESC,id);
-- index: social_posts_activity
CREATE INDEX social_posts_activity ON social_posts(last_activity_at DESC,id);
-- index: social_posts_views
CREATE INDEX social_posts_views ON social_posts(view_count DESC,last_activity_at DESC,id);
-- index: user_sessions_user_active
CREATE INDEX user_sessions_user_active ON user_sessions(user_id,expires_at,revoked_at);

-- Mark the schema as matching all application migrations.
INSERT INTO schema_migrations(version,name,applied_at) VALUES(1,'platform_identity_permissions_audit_outbox','2026-09-21T00:00:00.000Z');
INSERT INTO schema_migrations(version,name,applied_at) VALUES(2,'patients_profiles_and_archive_versions','2026-09-21T00:00:00.000Z');
INSERT INTO schema_migrations(version,name,applied_at) VALUES(3,'encounters_remote_consultations_and_media','2026-09-21T00:00:00.000Z');
INSERT INTO schema_migrations(version,name,applied_at) VALUES(4,'clinical_records_orders_and_hierarchical_reviews','2026-09-21T00:00:00.000Z');
INSERT INTO schema_migrations(version,name,applied_at) VALUES(5,'health_observations_plans_assessments_and_reminders','2026-09-21T00:00:00.000Z');
INSERT INTO schema_migrations(version,name,applied_at) VALUES(6,'isolated_opt_in_peer_community','2026-09-21T00:00:00.000Z');
INSERT INTO schema_migrations(version,name,applied_at) VALUES(7,'health_workflow_provenance_versions_and_receipts','2026-09-21T00:00:00.000Z');
INSERT INTO schema_migrations(version,name,applied_at) VALUES(8,'social_forums_bookmarks_notifications_and_conversations','2026-09-21T00:00:00.000Z');
INSERT INTO schema_migrations(version,name,applied_at) VALUES(9,'e_module_integrity_and_delivery_outbox','2026-09-21T00:00:00.000Z');
INSERT INTO schema_migrations(version,name,applied_at) VALUES(10,'social_post_views_and_sorting','2026-09-21T00:00:00.000Z');
INSERT INTO schema_migrations(version,name,applied_at) VALUES(11,'social_rich_content_attachments','2026-09-21T00:00:00.000Z');
INSERT INTO schema_migrations(version,name,applied_at) VALUES(12,'social_notification_events','2026-09-21T00:00:00.000Z');
INSERT INTO schema_migrations(version,name,applied_at) VALUES(13,'social_comment_reactions','2026-09-21T00:00:00.000Z');
INSERT INTO schema_migrations(version,name,applied_at) VALUES(14,'social_content_history_and_soft_deletion','2026-09-21T00:00:00.000Z');
INSERT INTO schema_migrations(version,name,applied_at) VALUES(15,'patients_editable_archives','2026-09-21T00:00:00.000Z');
INSERT INTO schema_migrations(version,name,applied_at) VALUES(16,'patients_registration_requests','2026-09-21T00:00:00.000Z');
INSERT INTO schema_migrations(version,name,applied_at) VALUES(17,'clinical_template_catalogue_and_record_history','2026-09-21T00:00:00.000Z');
INSERT INTO schema_migrations(version,name,applied_at) VALUES(18,'clinical_record_lifecycle_commands','2026-09-21T00:00:00.000Z');
INSERT INTO schema_migrations(version,name,applied_at) VALUES(19,'clinical_order_templates_and_receipts','2026-09-21T00:00:00.000Z');
INSERT INTO schema_migrations(version,name,applied_at) VALUES(20,'clinical_material_references','2026-09-21T00:00:00.000Z');
INSERT INTO schema_migrations(version,name,applied_at) VALUES(21,'platform_authentication_and_clinician_profiles','2026-09-21T00:00:00.000Z');
INSERT INTO schema_migrations(version,name,applied_at) VALUES(22,'demo_clinician_initial_password_123456','2026-09-21T00:00:00.000Z');
INSERT INTO schema_migrations(version,name,applied_at) VALUES(23,'health_observation_responsible_doctor_confirmation','2026-09-21T00:00:00.000Z');
INSERT INTO schema_migrations(version,name,applied_at) VALUES(24,'independent_password_email_and_face_sessions','2026-09-21T00:00:00.000Z');
COMMIT;
