import { mkdirSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { DatabaseSync } from 'node:sqlite';
import { migrations, openDatabase } from '../apps/api/src/database/connection.js';

const outputDir = resolve(process.cwd(), 'database');

function identifier(value: string): string {
  return `"${value.replaceAll('"', '""')}"`;
}

function literal(value: unknown): string {
  if (value === null) return 'NULL';
  if (typeof value === 'number' || typeof value === 'bigint') return String(value);
  if (value instanceof Uint8Array) return `X'${Buffer.from(value).toString('hex').toUpperCase()}'`;
  return `'${String(value).replaceAll("'", "''")}'`;
}

function schemaSql(database: DatabaseSync): string {
  const definitions = database
    .prepare(
      `SELECT type,name,sql FROM sqlite_schema
       WHERE sql IS NOT NULL AND name NOT LIKE 'sqlite_%'
       ORDER BY CASE type WHEN 'table' THEN 0 WHEN 'index' THEN 1 WHEN 'trigger' THEN 2 ELSE 3 END,name`,
    )
    .all() as Array<{ type: string; name: string; sql: string }>;
  const migrationRows = migrations.map(
    ({ version, name }) =>
      `INSERT INTO schema_migrations(version,name,applied_at) VALUES(${version},${literal(name)},'2026-09-21T00:00:00.000Z');`,
  );
  return [
    '-- CareLink SQLite schema snapshot. Generated by npm run database:export.',
    '-- Runtime source of truth: apps/api/src/**/**migration*.ts.',
    'PRAGMA foreign_keys=ON;',
    'BEGIN;',
    ...definitions.map(({ type, name, sql }) => `-- ${type}: ${name}\n${sql};`),
    '',
    '-- Mark the schema as matching all application migrations.',
    ...migrationRows,
    'COMMIT;',
    '',
  ].join('\n');
}

function seedSql(database: DatabaseSync): string {
  const tables = database
    .prepare(
      `SELECT name FROM sqlite_schema
       WHERE type='table' AND name NOT LIKE 'sqlite_%' AND name<>'schema_migrations'
       ORDER BY name`,
    )
    .all()
    .map((row) => String(row.name));
  const statements: string[] = [];
  for (const table of tables) {
    const columns = (
      database.prepare(`PRAGMA table_info(${identifier(table)})`).all() as Array<{
        name: string;
      }>
    ).map(({ name }) => name);
    if (!columns.length) continue;
    const rows = database
      .prepare(`SELECT ${columns.map(identifier).join(',')} FROM ${identifier(table)}`)
      .all() as Array<Record<string, unknown>>;
    rows.sort((left, right) =>
      JSON.stringify(columns.map((column) => left[column])).localeCompare(
        JSON.stringify(columns.map((column) => right[column])),
      ),
    );
    if (!rows.length) continue;
    statements.push(`-- ${table}: ${rows.length} row(s)`);
    for (const row of rows)
      statements.push(
        `INSERT INTO ${identifier(table)}(${columns.map(identifier).join(',')}) VALUES(${columns.map((column) => literal(row[column])).join(',')});`,
      );
    statements.push('');
  }
  return [
    '-- CareLink synthetic demonstration data. Generated by npm run database:export.',
    '-- Contains no real patient or clinician information.',
    'PRAGMA foreign_keys=OFF;',
    'BEGIN;',
    ...statements,
    'COMMIT;',
    'PRAGMA foreign_keys=ON;',
    '',
  ].join('\n');
}

mkdirSync(outputDir, { recursive: true });
const database = openDatabase(':memory:');
try {
  writeFileSync(resolve(outputDir, 'schema.sql'), schemaSql(database));
  writeFileSync(resolve(outputDir, 'seed.sql'), seedSql(database));
} finally {
  database.close();
}
